"""add departments

Revision ID: 61b92f37b816
Revises: 50fe4352fc59
Create Date: 2026-07-20 22:52:43.851768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61b92f37b816'
down_revision: Union[str, Sequence[str], None] = '50fe4352fc59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('tickets', sa.Column('department_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'departments', ['department_id'], ['id'])
    op.add_column('users', sa.Column('department_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'department_id')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'department_id')
    op.drop_table('departments')
    # ### end Alembic commands ###
